
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - python docs/source/build_images.py
      - python docs/source/build_viscm.py

sphinx:
  builder: html
  configuration: docs/source/conf.py

formats:
  - htmlzip
  - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
